# Generated by Django 2.0.3 on 2018-08-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180819_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExtraRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subextrasize', models.CharField(default='tmp', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subextrachoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_extra', to='orders.SubExtraChoice')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subextrarate',
            unique_together={('subextrachoice',)},
        ),
    ]
