# Generated by Django 2.0.3 on 2018-08-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180814_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrate',
            name='subsize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_size', to='orders.Size'),
        ),
    ]
