# Generated by Django 2.0.3 on 2018-08-19 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20180819_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatterRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dinnerplatterchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinnerplatter_choice', to='orders.DinnerPlatterChoice')),
                ('dinnerplattersize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinnerplatter_size', to='orders.Size')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menutype', models.CharField(default='pasta', editable='False', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menutype', models.CharField(default='pizza', editable='False', max_length=25)),
                ('pizzachoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizza_choice', to='orders.PizzaRate')),
                ('toppingchoice', models.ManyToManyField(related_name='pizza_topping', to='orders.ToppingChoice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizza_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menutype', models.CharField(default='sub', editable='False', max_length=25)),
                ('subchoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_choice', to='orders.SubRate')),
                ('subextrachoice', models.ManyToManyField(related_name='subextra_choice', to='orders.SubExtraRate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PastaRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastachoice', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SaladRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saladchoice', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='orderpasta',
            name='pastachoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasta_choice', to='orders.PastaRate'),
        ),
        migrations.AddField(
            model_name='orderpasta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasta_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
