# Generated by Django 2.0.3 on 2018-08-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20180819_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menutype', models.CharField(default='dinnerplatter', editable='False', max_length=25)),
                ('dinnerplatterchoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinnerplatter_choice', to='orders.DinnerPlatterRate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinnerplatter_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSalad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menutype', models.CharField(default='salad', editable='False', max_length=25)),
                ('saladchoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salad_choice', to='orders.SaladRate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salad_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
