# Generated by Django 2.0.3 on 2018-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderdinnerplatter_ordersalad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subextrarate',
            name='subextrachoice',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='SubExtraChoice',
        ),
    ]
