# Generated by Django 2.0.3 on 2018-08-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderpizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='toppingchoice',
            field=models.ManyToManyField(blank=True, related_name='pizza_topping', to='orders.ToppingChoice'),
        ),
    ]
