# Generated by Django 2.0.3 on 2018-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180814_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='toppingchoice',
            field=models.ManyToManyField(related_name='pizza_topping', to='orders.ToppingChoice'),
        ),
    ]
