# Generated by Django 2.0.3 on 2018-08-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180819_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subextrarate',
            name='subextrasize',
        ),
    ]
