# Generated by Django 2.0.3 on 2018-08-20 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_remove_subextrarate_subextrasize'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdinnerplatter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_dinnerplatter', to='orders.OrderDinnerPlatter')),
                ('orderpasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pasta', to='orders.OrderPasta')),
                ('orderpizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pizza', to='orders.OrderPizza')),
                ('ordersalad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_salad', to='orders.OrderSalad')),
                ('ordersub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_sub', to='orders.OrderSub')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placedorder_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
