# Generated by Django 2.0.3 on 2018-08-14 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_ordersub'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpizza',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizza_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
