# Generated by Django 2.0.3 on 2018-08-14 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_orderpizza_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinnerplatterchoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinnerplatter_choice', to='orders.DinnerPlatterRate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinnerplatter_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastachoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasta_choice', to='orders.PastaRate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasta_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSalad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saladchoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salad_choice', to='orders.SaladRate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salad_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
