# Generated by Django 2.0.3 on 2018-08-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180820_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdinnerplatter',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpasta',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersalad',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersub',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
