# Generated by Django 2.0.3 on 2018-08-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderdinnerplatter_orderpasta_ordersalad'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpizza',
            name='menutype',
            field=models.CharField(default='pizza', editable='False', max_length=25),
        ),
    ]
