# Generated by Django 2.0.3 on 2018-08-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderpizza_menutype'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdinnerplatter',
            name='menutype',
            field=models.CharField(default='dinnerplatter', editable='False', max_length=25),
        ),
        migrations.AddField(
            model_name='orderpasta',
            name='menutype',
            field=models.CharField(default='pasta', editable='False', max_length=25),
        ),
        migrations.AddField(
            model_name='ordersalad',
            name='menutype',
            field=models.CharField(default='salad', editable='False', max_length=25),
        ),
        migrations.AddField(
            model_name='ordersub',
            name='menutype',
            field=models.CharField(default='sub', editable='False', max_length=25),
        ),
    ]
