# Generated by Django 2.0.3 on 2018-08-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180820_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
