# Generated by Django 2.0.3 on 2018-10-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_placedorder_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
