# Generated by Django 2.0.3 on 2018-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20181007_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
