# Generated by Django 2.0.3 on 2018-10-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20181009_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='deliveryaddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address', to='orders.DeliveryAddress'),
        ),
    ]
